route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: email-me

  routes:
    - receiver: email-me
      match:
        alertname: PrometheusTargetMissing

receivers:
- name: email-me
  email_configs:
  - to: eugeny.v.ovchinnikov@gmail.com
    from: ovchinnikov.john@yandex.ru
    smarthost: smtp.yandex.ru:465
    require_tls: false
    auth_username: ovchinnikov.john
    auth_identity: ovchinnikov.john
    auth_password: **********